name: PHP Composer

on:
    push:
      branches: [ main, new-branche ]
    pull_request:
      branches: [ main, new-branche ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install composer init
      run: composer require
      
    - name: install composer
      run: composer install 
      
    - name: install phpunit
      run: composer require --dev phpunit/phpunit  
      
    - name: update composer
      run: composer update
      
    - name: pecl install pcov
      run: pecl install pcov
      
    - name: test
      run: composer exec phpunit test.php
